# example netlify.toml
[build]
  command = "nx build ufw-blog"
  functions = "apps/ufw-blog/netlify/functions"
  base = "."
  publish = "dist/apps/ufw-blog"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://docs.netlify.com/configure-builds/file-based-configuration/
